import { RecipeExposureGroupResponse } from '@/models/shop/recipe';

export const MOCK_DATA: RecipeExposureGroupResponse = {
    groupId: '1',
    groups: [
        {
            sno: 1,
            groupName: 'Sponsored Meals',
            description:
                '영양 균형이 잘 잡힌 한 끼 식사 레시피를 소개합니다. 간단하지만 건강한 요리들을 만나보세요.',
            sortOrder: 1,
            isDisplay: true,
            recipes: [
                {
                    sno: 101,
                    memberNo: 1,
                    liked: false,
                    bookmarked: false,
                    likeCount: 124,
                    bookmarkCount: 38,
                    memberName: '요리왕',
                    memberId: 'chef_king',
                    title: '연탄 야채 볶음기',
                    description: '불향 가득한 야채 볶음',
                    sourceType: 'MANUAL',
                    authorName: '요리왕',
                    durationSeconds: 1800,
                    servings: 2,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=500&fit=crop',
                    regDt: '2024-01-01T00:00:00Z',
                    updateDt: '2024-01-01T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 102,
                    memberNo: 2,
                    liked: true,
                    bookmarked: false,
                    likeCount: 87,
                    bookmarkCount: 22,
                    memberName: '집밥러버',
                    memberId: 'home_cook',
                    title: '순두부찌개',
                    description: '얼큰하고 부드러운 순두부찌개',
                    sourceType: 'MANUAL',
                    authorName: '집밥러버',
                    durationSeconds: 1200,
                    servings: 1,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400&h=500&fit=crop',
                    regDt: '2024-01-02T00:00:00Z',
                    updateDt: '2024-01-02T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 103,
                    memberNo: 3,
                    liked: false,
                    bookmarked: true,
                    likeCount: 203,
                    bookmarkCount: 61,
                    memberName: '미식가',
                    memberId: 'foodie',
                    title: '계란 후라이 덮밥',
                    description: '간단하고 든든한 한 끼',
                    sourceType: 'MANUAL',
                    authorName: '미식가',
                    durationSeconds: 600,
                    servings: 1,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400&h=500&fit=crop',
                    regDt: '2024-01-03T00:00:00Z',
                    updateDt: '2024-01-03T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 104,
                    memberNo: 1,
                    liked: false,
                    bookmarked: false,
                    likeCount: 56,
                    bookmarkCount: 14,
                    memberName: '요리왕',
                    memberId: 'chef_king',
                    title: '시금치 나물 무침',
                    description: '참기름 향 가득한 나물 반찬',
                    sourceType: 'MANUAL',
                    authorName: '요리왕',
                    durationSeconds: 900,
                    servings: 4,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=500&fit=crop',
                    regDt: '2024-01-04T00:00:00Z',
                    updateDt: '2024-01-04T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 105,
                    memberNo: 4,
                    liked: true,
                    bookmarked: false,
                    likeCount: 342,
                    bookmarkCount: 99,
                    memberName: '쉐프박',
                    memberId: 'chef_park',
                    title: '된장찌개',
                    description: '구수하고 깊은 맛의 된장찌개',
                    sourceType: 'MANUAL',
                    authorName: '쉐프박',
                    durationSeconds: 1500,
                    servings: 2,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=500&fit=crop',
                    regDt: '2024-01-05T00:00:00Z',
                    updateDt: '2024-01-05T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 106,
                    memberNo: 2,
                    liked: false,
                    bookmarked: false,
                    likeCount: 78,
                    bookmarkCount: 19,
                    memberName: '집밥러버',
                    memberId: 'home_cook',
                    title: '감자조림',
                    description: '달콤짭짤한 감자조림',
                    sourceType: 'MANUAL',
                    authorName: '집밥러버',
                    durationSeconds: 1800,
                    servings: 3,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&h=500&fit=crop',
                    regDt: '2024-01-06T00:00:00Z',
                    updateDt: '2024-01-06T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 107,
                    memberNo: 5,
                    liked: true,
                    bookmarked: true,
                    likeCount: 512,
                    bookmarkCount: 120,
                    memberName: '파스타마스터',
                    memberId: 'pasta_master',
                    title: '봉골레 파스타',
                    description: '조개의 깊은 풍미를 살린 오일 파스타',
                    sourceType: 'MANUAL',
                    authorName: '파스타마스터',
                    durationSeconds: 1200,
                    servings: 2,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1473093226795-af9932fe5856?w=400&h=500&fit=crop',
                    regDt: '2024-01-07T00:00:00Z',
                    updateDt: '2024-01-07T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 108,
                    memberNo: 3,
                    liked: false,
                    bookmarked: false,
                    likeCount: 45,
                    bookmarkCount: 8,
                    memberName: '미식가',
                    memberId: 'foodie',
                    title: '그릭 샐러드',
                    description: '신선한 채소와 페타 치즈의 조화',
                    sourceType: 'MANUAL',
                    authorName: '미식가',
                    durationSeconds: 600,
                    servings: 1,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=500&fit=crop',
                    regDt: '2024-01-08T00:00:00Z',
                    updateDt: '2024-01-08T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 109,
                    memberNo: 6,
                    liked: true,
                    bookmarked: false,
                    likeCount: 890,
                    bookmarkCount: 215,
                    memberName: '베이킹퀸',
                    memberId: 'baking_queen',
                    title: '초코칩 쿠키',
                    description: '겉바속촉 달콤한 초코칩 쿠키',
                    sourceType: 'MANUAL',
                    authorName: '베이킹퀸',
                    durationSeconds: 2700,
                    servings: 12,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400&h=500&fit=crop',
                    regDt: '2024-01-09T00:00:00Z',
                    updateDt: '2024-01-09T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 110,
                    memberNo: 1,
                    liked: false,
                    bookmarked: false,
                    likeCount: 156,
                    bookmarkCount: 42,
                    memberName: '요리왕',
                    memberId: 'chef_king',
                    title: '김치볶음밥',
                    description: '한국인의 소울푸드',
                    sourceType: 'MANUAL',
                    authorName: '요리왕',
                    durationSeconds: 900,
                    servings: 1,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400&h=500&fit=crop',
                    regDt: '2024-01-10T00:00:00Z',
                    updateDt: '2024-01-10T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 111,
                    memberNo: 7,
                    liked: true,
                    bookmarked: true,
                    likeCount: 1230,
                    bookmarkCount: 450,
                    memberName: '고기덕후',
                    memberId: 'meat_lover',
                    title: '스테이크 굽기',
                    description: '집에서 즐기는 완벽한 미디엄 레어',
                    sourceType: 'MANUAL',
                    authorName: '고기덕후',
                    durationSeconds: 1800,
                    servings: 1,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1546241072-48010ad28c2c?w=400&h=500&fit=crop',
                    regDt: '2024-01-11T00:00:00Z',
                    updateDt: '2024-01-11T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 112,
                    memberNo: 2,
                    liked: false,
                    bookmarked: false,
                    likeCount: 67,
                    bookmarkCount: 12,
                    memberName: '집밥러버',
                    memberId: 'home_cook',
                    title: '미역국',
                    description: '부드럽고 깊은 국물 맛',
                    sourceType: 'MANUAL',
                    authorName: '집밥러버',
                    durationSeconds: 2400,
                    servings: 4,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=500&fit=crop',
                    regDt: '2024-01-12T00:00:00Z',
                    updateDt: '2024-01-12T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 113,
                    memberNo: 8,
                    liked: true,
                    bookmarked: false,
                    likeCount: 215,
                    bookmarkCount: 56,
                    memberName: '브런치요정',
                    memberId: 'brunch_fairy',
                    title: '에그 베네딕트',
                    description: '홀란다이즈 소스를 곁들인 고급 브런치',
                    sourceType: 'MANUAL',
                    authorName: '브런치요정',
                    durationSeconds: 1500,
                    servings: 2,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1600335895229-6e75511892c8?w=400&h=500&fit=crop',
                    regDt: '2024-01-13T00:00:00Z',
                    updateDt: '2024-01-13T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 114,
                    memberNo: 4,
                    liked: false,
                    bookmarked: false,
                    likeCount: 98,
                    bookmarkCount: 23,
                    memberName: '쉐프박',
                    memberId: 'chef_park',
                    title: '제육볶음',
                    description: '매콤달콤한 밥도둑',
                    sourceType: 'MANUAL',
                    authorName: '쉐프박',
                    durationSeconds: 1200,
                    servings: 2,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=500&fit=crop',
                    regDt: '2024-01-14T00:00:00Z',
                    updateDt: '2024-01-14T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 115,
                    memberNo: 9,
                    liked: true,
                    bookmarked: true,
                    likeCount: 670,
                    bookmarkCount: 180,
                    memberName: '커피마니아',
                    memberId: 'coffee_mania',
                    title: '티라미수',
                    description: '입안에서 살살 녹는 디저트',
                    sourceType: 'MANUAL',
                    authorName: '커피마니아',
                    durationSeconds: 3600,
                    servings: 6,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=500&fit=crop',
                    regDt: '2024-01-15T00:00:00Z',
                    updateDt: '2024-01-15T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 116,
                    memberNo: 1,
                    liked: false,
                    bookmarked: false,
                    likeCount: 112,
                    bookmarkCount: 28,
                    memberName: '요리왕',
                    memberId: 'chef_king',
                    title: '잔치국수',
                    description: '깔끔한 멸치 육수의 감칠맛',
                    sourceType: 'MANUAL',
                    authorName: '요리왕',
                    durationSeconds: 1200,
                    servings: 2,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1552611052-33e04de081de?w=400&h=500&fit=crop',
                    regDt: '2024-01-16T00:00:00Z',
                    updateDt: '2024-01-16T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 117,
                    memberNo: 10,
                    liked: true,
                    bookmarked: false,
                    likeCount: 432,
                    bookmarkCount: 89,
                    memberName: '일식전문가',
                    memberId: 'sushi_pro',
                    title: '규동',
                    description: '부드러운 소고기 덮밥',
                    sourceType: 'MANUAL',
                    authorName: '일식전문가',
                    durationSeconds: 1200,
                    servings: 1,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1562607311-4770335e40e6?w=400&h=500&fit=crop',
                    regDt: '2024-01-17T00:00:00Z',
                    updateDt: '2024-01-17T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 118,
                    memberNo: 5,
                    liked: false,
                    bookmarked: false,
                    likeCount: 167,
                    bookmarkCount: 34,
                    memberName: '파스타마스터',
                    memberId: 'pasta_master',
                    title: '까르보나라',
                    description: '정통 방식의 고소한 크림 파스타',
                    sourceType: 'MANUAL',
                    authorName: '파스타마스터',
                    durationSeconds: 1500,
                    servings: 1,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400&h=500&fit=crop',
                    regDt: '2024-01-18T00:00:00Z',
                    updateDt: '2024-01-18T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 119,
                    memberNo: 3,
                    liked: true,
                    bookmarked: true,
                    likeCount: 543,
                    bookmarkCount: 112,
                    memberName: '미식가',
                    memberId: 'foodie',
                    title: '아보카도 토스트',
                    description: '건강하고 든든한 아침 식사',
                    sourceType: 'MANUAL',
                    authorName: '미식가',
                    durationSeconds: 600,
                    servings: 1,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&h=500&fit=crop',
                    regDt: '2024-01-19T00:00:00Z',
                    updateDt: '2024-01-19T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
                {
                    sno: 120,
                    memberNo: 6,
                    liked: false,
                    bookmarked: false,
                    likeCount: 231,
                    bookmarkCount: 47,
                    memberName: '베이킹퀸',
                    memberId: 'baking_queen',
                    title: '애플 파이',
                    description: '시나몬 향이 가득한 달콤한 파이',
                    sourceType: 'MANUAL',
                    authorName: '베이킹퀸',
                    durationSeconds: 4500,
                    servings: 8,
                    thumbnailUrl:
                        'https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=400&h=500&fit=crop',
                    regDt: '2024-01-20T00:00:00Z',
                    updateDt: '2024-01-20T00:00:00Z',
                    recipeStatus: 'COMPLETED',
                    ownershipType: 'CREATED',
                    failureReason: null,
                },
            ],

        },
    ],
};
