export const BANNER_ID = {
    LOGO: 'LOGO',
    MAIN_TOP: 'MAIN_TOP',
    MOBILE_MAIN_TOP: 'MOBILE_MAIN_TOP',
    MAIN_HEADER: 'MAIN_HEADER',
    MOBILE_MAIN_HEADER: 'MOBILE_MAIN_HEADER',
    MD_PICK: 'MD_PICK',
    MAIN_EVENT: 'MAIN_EVENT',
    MOBILE_MAIN_EVENT: 'MOBILE_MAIN_EVENT',
    MAIN_ICON: 'MAIN_ICON',
    MAIN_EXHIBITION: 'MAIN_EXHIBITION',
};

export const BROWSER_TARGET_TYPE = {
    CURRENT: 'CURRENT',
    NEW: 'NEW',
};
