const EVENT_LIST = {
    DEFAULT_PAGE_NUMBER: '1',
    DEFAULT_PAGE_SIZE: '15',
};

const EVENT_PRODUCT_SECTION = {
    DEFAULT_PAGE_NUMBER_LIST: [1, 2, 3],
    DEFAULT_PAGE_SIZE: 30,
    PC_PER_ROW: 5,
    MOBILE_PER_ROW: 2,
};

export { EVENT_LIST, EVENT_PRODUCT_SECTION };
