export const OVERLAY_ID = {
    OPTION_BOTTOM_SHEET: 'option-bottom-sheet',
    BOTTOM_NAV_DRAWER: 'bottom-nav-drawer',
    CATEGORY_DRAWER: 'category-drawer',
    SEARCH_DRAWER: 'search-drawer',
    CATEGORY_DROPDOWN: 'category-dropdown',
    ADD_TO_CART: 'add-to-cart',
    OVERSEAS_DELIVERABLE: 'overseas-deliverable',
    QUERY_SELECTOR: 'query-selector',
    PERIOD_BOTTOM_SHEET: 'period-list-bottom-sheet',
    CALENDAR_BOTTOM_SHEET: 'calendar-list-bottom-sheet',
    PI_RESTOCK_NOTICE_MODAL: 'pi-restock-notice-modal',
    TOAST: 'toast',
    LOADING: 'loading',
    COLLECTION_FORM: 'collection-form',
    ORDER_COMPLETE_RECIPE_RECOMMENDATION:
        'order-complete-recipe-recommendation',
    ORDER_COMPLETE_RECIPE_RECOMMENDATION_BOTTOM_SHEET:
        'order-complete-recipe-recommendation-bottom-sheet',
    LOGIN_DIALOG: 'login-dialog',
    RECIPE_URL_INPUT: 'recipe-url-input',
    RECIPE_IMAGE_UPLOAD: 'recipe-image-upload',
    IMAGE_DETAIL: 'image-detail',
    RECIPE_CREATE_SELECTION: 'recipe-create-selection',
    RECIPE_SAVE: 'recipe-save',
    SHIPPING_ADDRESS_CHANGE: 'shipping-address-change',
} as const;
