import { dehydrate } from '@tanstack/react-query';
import type { Metadata } from 'next';
import { OverlayProvider } from 'overlay-kit';
import { isEmpty } from '@fxts/core';

import Footer from '@/components/common/Footer';
import Header from '@/components/common/Header';
import MobileBottomNavigation from '@/components/common/MobileBottomNavigation';
import GlobalErrorBoundary from '@/components/GlobalErrorBoundary';
import I18nProvider from '@/providers/I18nProvider';
import QueryProvider from '@/providers/QueryProvider';
import { css } from '@/styled-system/css';
import { makeQueryClient } from '@/utils/queryClient';
import GlobalEffects from '@/components/common/GlobalEffects';
import { category } from '@/api/display';
import { categoryKeys } from '@/hooks/queryKeys';

import '@/app/globals.css';
import 'swiper/css';
import 'swiper/css/effect-coverflow';
import 'swiper/css/navigation';

export const metadata: Metadata = {
    title: 'WannaMake',
    description: 'Generated by create next app',
};

// Footer 데이터 revalidation 설정 (1시간)
export const revalidate = 3600;

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const locale = process.env.NEXT_PUBLIC_LOCALE || 'ko';

    const queryClient = makeQueryClient();

    try {
        const response = await category
            .getCategoriesByManagementCode({ codes: ['MAIN'] })
            .json();

        const categoryNo = response?.[0]?.displayCategoryNo ?? 0;

        if (categoryNo) {
            queryClient.setQueryData(
                categoryKeys.byCode({ codes: ['MAIN'] }),
                response,
            );

            const categoryResponse = await category
                .getCategory(categoryNo.toString())
                .json();

            if (!isEmpty(categoryResponse?.multiLevelCategories)) {
                queryClient.setQueryData(
                    categoryKeys.detail(categoryNo.toString()),
                    categoryResponse,
                );
            }
        }
    } catch (error) {
        console.error(error);
    }

    const dehydratedState = dehydrate(queryClient);

    return (
        <html lang={locale}>
            <body>
                <I18nProvider>
                    <QueryProvider dehydratedState={dehydratedState}>
                        <OverlayProvider>
                            <GlobalErrorBoundary>
                                <Header />
                                <main
                                    className={css({
                                        flex: 1,
                                        width: '100%',
                                        maxWidth: {
                                            base: '100%',
                                            lg: '1200px',
                                        },
                                        marginX: 'auto',
                                    })}
                                >
                                    {children}
                                </main>
                                <Footer />
                                <MobileBottomNavigation />
                                <GlobalEffects />
                            </GlobalErrorBoundary>
                        </OverlayProvider>
                    </QueryProvider>
                </I18nProvider>
            </body>
        </html>
    );
}
