import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { OverlayProvider } from 'overlay-kit';

import '@/app/globals.css';
import Footer from '@/components/Footer';
import GlobalErrorBoundary from '@/components/GlobalErrorBoundary';
import Header from '@/components/Header';
import MobileBottomNavigation from '@/components/MobileBottomNavigation';
import QueryProvider from '@/providers/QueryProvider';
import { css } from '@/styled-system/css';

export const metadata: Metadata = {
    title: '제니지니앤로이드',
    description: 'Generated by create next app',
};

// Footer 데이터 revalidation 설정 (1시간)
export const revalidate = 3600;

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const locale = process.env.NEXT_PUBLIC_LOCALE || 'ko';
    const messages = await getMessages();

    return (
        <html lang={locale}>
            <body>
                <NextIntlClientProvider messages={messages}>
                    <OverlayProvider>
                        <QueryProvider>
                            <GlobalErrorBoundary>
                                <Header />
                                <main
                                    className={css({
                                        flex: 1,
                                        width: '100%',
                                        maxWidth: {
                                            base: '100%',
                                            lg: '1200px',
                                        },
                                        marginX: 'auto',
                                    })}
                                >
                                    {children}
                                </main>
                                <Footer />
                                <MobileBottomNavigation />
                            </GlobalErrorBoundary>
                        </QueryProvider>
                    </OverlayProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
