import { dehydrate } from '@tanstack/react-query';
import type { Metadata } from 'next';
import { OverlayProvider } from 'overlay-kit';

import Footer from '@/components/common/Footer';
import Header from '@/components/common/Header';
import MobileBottomNavigation from '@/components/common/MobileBottomNavigation';
import GlobalErrorBoundary from '@/components/GlobalErrorBoundary';
import I18nProvider from '@/providers/I18nProvider';
import QueryProvider from '@/providers/QueryProvider';
import { css } from '@/styled-system/css';
import { makeQueryClient } from '@/utils/queryClient';

import '@/app/globals.css';
import 'swiper/css';
import 'swiper/css/effect-coverflow';
import 'swiper/css/navigation';

export const metadata: Metadata = {
    title: 'WannaMake',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const locale = process.env.NEXT_PUBLIC_LOCALE || 'ko';

    const queryClient = makeQueryClient();

    const dehydratedState = dehydrate(queryClient);

    return (
        <html lang={locale}>
            <body>
                <I18nProvider>
                    <QueryProvider dehydratedState={dehydratedState}>
                        <OverlayProvider>
                            <GlobalErrorBoundary>
                                <Header />
                                <main
                                    className={css({
                                        flex: 1,
                                        width: '100%',
                                        maxWidth: {
                                            base: '100%',
                                            lg: '1440px',
                                        },
                                        marginX: 'auto',
                                    })}
                                >
                                    {children}
                                </main>
                                <Footer />
                                <MobileBottomNavigation />
                            </GlobalErrorBoundary>
                        </OverlayProvider>
                    </QueryProvider>
                </I18nProvider>
            </body>
        </html>
    );
}
